import dynamic from 'next/dynamic';
import Head from 'next/head';

const PDFViewer = dynamic(() => import('../components/pdf-viewer'), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PDFViewer />
    </>
  );
}
